"""
Constants for use in our notebooks
"""

from pathlib import Path

DATA_ROOT = Path(__file__).parents[2] / "data"

CEDS_PROCESSING_ID = "0001"
CEDS_EXPECTED_NUMBER_OF_REGION_VARIABLE_PAIRS_IN_GLOBAL_HARMONIZATION = 2

GFED_PROCESSING_ID = "0001"

GCB_PROCESSING_ID = "0001"

VELDERS_ET_AL_2022_PROCESSING_ID = "0001"

ADAM_ET_AL_2024_PROCESSING_ID = "0001"

WMO_2022_PROCESSING_ID = "0001"

EDGAR_PROCESSING_ID = "0001"

COMBINED_HISTORY_ID = "0002"

IAMC_REGION_PROCESSING_ID = "0002"

HARMONISATION_ID = "0001"

INFILLING_SILICONE_ID = "0001"

INFILLING_WMO_ID = "0001"

INFILLING_LEFTOVERS_ID = "0001"

# Chosen to match the CMIP experiment ID
HISTORY_SCENARIO_NAME = "historical"
